/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1d",
        "primary": "#012d1d",
        "surface-container-high": "#e7e8e9",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdcbd",
        "surface-container-low": "#f3f4f5",
        "outline": "#717973",
        "on-primary-container": "#86af99",
        "on-surface-variant": "#414844",
        "on-primary-fixed": "#002114",
        "surface-container-highest": "#e1e3e4",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#693b1d",
        "tertiary": "#3b1f00",
        "on-secondary-container": "#794829",
        "on-tertiary-container": "#cd9d6d",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#274e3d",
        "surface-variant": "#e1e3e4",
        "on-background": "#191c1d",
        "secondary-fixed": "#ffdbc8",
        "surface": "#f8f9fa",
        "secondary-container": "#fdbb93",
        "on-secondary-fixed": "#321300",
        "on-tertiary-fixed": "#2c1600",
        "surface-tint": "#3f6653",
        "primary-fixed-dim": "#a5d0b9",
        "primary-container": "#1b4332",
        "outline-variant": "#c1c8c2",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#c1ecd4",
        "tertiary-container": "#56340e",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#623f18",
        "surface-container": "#edeeef",
        "surface-dim": "#d9dadb",
        "secondary-fixed-dim": "#fab890",
        "secondary": "#855232",
        "background": "#f8f9fa",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#a5d0b9",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#f0bd8b",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "unit": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "gutter": "24px",
        "lg": "24px",
        "xl": "48px",
        // "max_width": "1200px",
      },
      fontFamily: {
        "h1": ["Public Sans", "sans-serif"],
        "h2": ["Public Sans", "sans-serif"],
        "h3": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
